version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anygrab-api
    restart: unless-stopped
    environment:
      - TZ=UTC
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/docs > /dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    # If you want tmp storage:
    # volumes:
    #   - ./data:/tmp/anygrab

  web:
    image: caddy:2.7
    container_name: anygrab-web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/srv                    # serve your index.html & assets
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
