version: "3.9"

services:
  anydownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anydownloader
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # Persist downloaded files on the host
      - ./downloads:/app/downloads
      # If you serve static/templates, uncomment these:
      # - ./static:/app/static
      # - ./templates:/app/templates
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
